### ISSUE TITLE
Adds 2 extra layers

### ISSUE THREAD

**Issue by Efekent** [chatrat12/layerdisplay#4]
Slicing with Simplify3D and Layerdisplay shows 2 more layers than Simplify3D.

For example: Simplify3D says there is 89 layers and Layerdisplay shows 91 layers.
Also Layerdisplay shows layer 3 is being printed while in real layer 1 is being printed.

I am using OctoPrint 1.3.9 running on OctoPi 0.15.1 (latest release) 

Gcode is included in the zip file
[6xSmall_Scoop4Max.zip](https://github.com/chatrat12/layerdisplay/files/2239068/6xSmall_Scoop4Max.zip)

**Comment by prgmatic** [comment]
Yeah, usually I get one extra layer. My Mk2.5 does a purge line and it is usually at a different heght than my first layer hence the extra layer. 2 extra layers is a bit more annoying than just one. I try to keep the logic on the GCode analyzer as slim so it runs and quickly as possible. Trying to detect purges could slow it down. I'm not in front of my PC, I'll take a look at your GCode when I get a chance and see if there is a cheap way for me to exclude purges.

**Comment by Efekent** [comment]
Thank you, there is no rush take your time, I just wanted contribute information, now you mentioned it I also use this code in my starting script:
`G1 X150 E15 F500        ;Extrude 13mm filiment along X axis 143mm long to prime and clean the nozzle`
Probably that is the reason why it adds one more layer than usual on my display.

It is great script, thanks for that!

**Comment by prgmatic** [comment]
I came up with a cheap way to detect purge layers. The GCode analyzer now counts how many extrude commands happen on any given layer. I set the first layer to require a minimum of 3 extrusion commands to be considered the first layer. This should work in %99.9 of cases. I it set require 3 since Prusa printers commonly purge in 2 extrusions on the same layer height. In the future, I may give users the ability to tweak this setting. I could see a user wanting the first layer to require more extrude commands than just 3. 

@Efekent Thank you for your feedback :) Layer display now has 2 less layers for your GCode file. :D

These changes are in the 0.4.0 release. If you are not automatically prompted by OctoPrint to update, you can find the update in the 'Software Update' tab in the settings panel.

**Comment by Efekent** [comment]
Thanks @chatrat12 👍  I will update soon as I can, (Doing a big print right now) I think the idea to give users ability to put values in the settings is great, this morning I printed with my smaller printer and there is no purge layer so the count was exactly as in the slicer. 
So it might be different for some users and being able to put a offset value to correct that would be neat.

**Comment by prgmatic** [comment]
Your print that had no purges will still have the correct layer count in the new update. The only 2 cases where it can break down is if your first layer only has 2 lines in it which is extremely unlikely, or if your purge has more than 2 extrusions at the same z height. Should cover %99 use cases without needing to tweak any setting. Users would only need to tweak it if they have longer purge routines (if any).

**Comment by Efekent** [comment]
Thanks @chatrat12 my print was finally finished and started a new one, the layer displays shows correct now on same printer with same slicing software.
